import Head from "next/head";
import useAuth from "@/utils/hooks/useAuth";
import { GetServerSideProps } from "next";
import { parseCookies } from "nookies";
import getUser from "@/utils/user/getUser";
import { formatPrisma } from "@/services/formatPrisma";
import Navbar from "@/components/Navbar";
import { User } from "@/types/Auth";
import Main from "@/components/main/Main";
import { Stack } from "@mui/material";
import NewToDo from "@/components/NewToDo/NewToDo";

type HomeProps = {
  user: User;
};

export default function Home({ user }: HomeProps) {
  return (
    <>
      <Head>
        <title>My notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar username={user.username} />
      <NewToDo />
      <Main />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { "nextauth.token": authToken, "nextauth.id": idToken } =
    parseCookies(ctx);

  if (!authToken) {
    return {
      redirect: {
        destination: "/signin",
        permanent: false,
      },
    };
  }
  const user = await getUser({ id: idToken });

  return {
    props: { user },
  };
};
